root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = ["-config", "configs/veli.yaml"]
bin = "./tmp/api"
cmd = "go build -o ./tmp/api ./cmd/api"
delay = 100
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
exclude_regex = ["_test.go"]
include_ext = ["go", "yaml", "yml", "sql"]
log = "build-errors.log"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = false
