// Package db owns the runtime database boundary for the Veḷi API:
// opening a pgx connection pool from config, applying goose migrations
// from the embedded migrations FS, and orderly shutdown.
//
// Repository code lives one layer up (in internal/repository/) and
// depends on the *pgxpool.Pool exposed here. Anything generated by Bob
// will live under internal/database/, separate from this hand-written
// connection plumbing.
package db

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/cloudparallax/veli/internal/config"
)

// Open parses cfg.DSN, applies the configured pool sizing, and verifies
// the connection with a Ping under a five-second timeout. The caller
// owns the pool and must Close it on shutdown.
func Open(ctx context.Context, cfg config.DatabaseConfig) (*pgxpool.Pool, error) {
	poolCfg, err := pgxpool.ParseConfig(cfg.DSN)
	if err != nil {
		return nil, fmt.Errorf("parse dsn: %w", err)
	}
	if cfg.MaxOpenConns > 0 {
		poolCfg.MaxConns = int32(cfg.MaxOpenConns)
	}
	if cfg.MaxIdleConns > 0 {
		poolCfg.MinConns = int32(cfg.MaxIdleConns)
	}
	if cfg.ConnMaxLifetime > 0 {
		poolCfg.MaxConnLifetime = cfg.ConnMaxLifetime
	}

	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("pgxpool new: %w", err)
	}

	pingCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("db ping: %w", err)
	}

	return pool, nil
}
